name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Install .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
           dotnet-version: '8.0.x'
           dotnet-quality: 'preview'

      # Publish the site
      - name: Publish
        run: dotnet publish SampleApps/BlazorWasmApp1/BlazorWasmApp1.csproj -c Release -o public -p GHPages=true --nologo

      # Deploy the site
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/wwwroot
          force_orphan: true